// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using is4FirstDemo.IdentityUserStore;

namespace is4FirstDemo.Data.Migrations.IdentityServer.UserDb
{
    [DbContext(typeof(UserStoreDbContext1))]
    [Migration("20201223063523_InitialIdentityServerIdentityUserDbMigration1")]
    partial class InitialIdentityServerIdentityUserDbMigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("is4FirstDemo.IdentityUserStore.IdentityUser1", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderSubjectId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SubjectId");

                    b.ToTable("IdentityUser");
                });

            modelBuilder.Entity("is4FirstDemo.IdentityUserStore.IdentityUserClaim1", b =>
                {
                    b.Property<string>("ClaimId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserSubjectId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ClaimId");

                    b.HasIndex("UserSubjectId");

                    b.ToTable("IdentityUserClaim");
                });

            modelBuilder.Entity("is4FirstDemo.IdentityUserStore.IdentityUserClaim1", b =>
                {
                    b.HasOne("is4FirstDemo.IdentityUserStore.IdentityUser1", "IdentityUser")
                        .WithMany("IdentityUserClaims")
                        .HasForeignKey("UserSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
